version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
