import { defineConfig, loadEnv, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';
import { resolve } from 'path';

/**
 * Resolve the API origin from VITE_API_URL (process env first, so CI's build
 * env wins over any checked-in .env), or null when it is not configured.
 */
function apiOrigin(mode: string): string | null {
  const raw = process.env.VITE_API_URL || loadEnv(mode, __dirname, 'VITE_').VITE_API_URL || '';
  if (!raw) return null;
  try {
    return new URL(raw).origin;
  } catch {
    throw new Error(`VITE_API_URL is not an absolute URL: ${raw}`);
  }
}

/**
 * Substitute the API origin into index.html's two markers.
 *
 * index.html used to hardcode the dev loopback API address in a `preconnect`
 * hint and in the meta CSP, with a comment promising a build-time override
 * that nothing performed — so production shipped a plaintext-http resource
 * hint pointing at a developer's machine, on an https page.
 *
 * The rules here make that unrepresentable:
 *   - `preconnect` is emitted only for an https origin, so a build can never
 *     hint at a loopback address (and there is nothing to preconnect to when
 *     the API origin is unknown);
 *   - the CSP marker takes the origin only while the dev server is running,
 *     where the API is plain http and the policy's `https:` source expression
 *     does not cover it. In a build the deployed API is https, which `https:`
 *     already allows, so the marker resolves to nothing.
 *
 * `scripts/check-seo-build.mjs` fails the build if either marker survives
 * unsubstituted, or if any built HTML names a loopback address.
 */
function apiOriginHtml(mode: string): Plugin {
  return {
    name: 'family-greenhouse:api-origin-html',
    transformIndexHtml: {
      order: 'pre',
      handler(html, ctx) {
        const serving = ctx.server != null;
        const origin = apiOrigin(mode) ?? (serving ? 'http://localhost:4000' : null);
        const https = origin?.startsWith('https://') ?? false;
        const preconnect = https ? `<link rel="preconnect" href="${origin}" crossorigin />` : '';
        const cspOrigin = serving && origin && !https ? `${origin} ` : '';
        return html
          .replace('<!-- __API_PRECONNECT__ -->', preconnect)
          .replaceAll('__API_ORIGIN__ ', cspOrigin);
      },
    },
  };
}

export default defineConfig(({ mode }) => ({
  plugins: [
    react(),
    apiOriginHtml(mode),
    VitePWA({
      registerType: 'autoUpdate',
      // Registration is imported from services/pwaRegistration so rejected
      // browser registrations are handled instead of becoming page errors.
      injectRegister: null,
      includeAssets: [
        'brand/favicon.ico',
        'brand/favicon-32x32.png',
        'brand/icon.svg',
        'brand/apple-touch-icon.png',
        'robots.txt',
      ],
      manifest: {
        name: 'Family Greenhouse',
        short_name: 'Greenhouse',
        description:
          'Collaborative household plant care with free accounts for up to 10 plants. Share tasks, reminders, and care history.',
        // Forest browser chrome + the cooler daylight surface match the
        // native icon and launch artwork generated by render-brand-assets.sh.
        theme_color: '#173404',
        background_color: '#F7F8F2',
        display: 'standalone',
        start_url: '/',
        icons: [
          { src: '/brand/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: '/brand/icon-512.png', sizes: '512x512', type: 'image/png' },
          // Maskable variant: the on-green plate gives Android safe-zone
          // padding so the icon doesn't get clipped by aggressive home-
          // screen masks.
          {
            src: '/brand/icon-512-on-green.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Workbox owns the generated app-shell worker; keep push behavior in
        // a small, independently testable classic worker that it imports.
        importScripts: ['push-handler.js'],
        // Take over as soon as the new SW installs instead of waiting for
        // every tab to close. Without this, a deploy can leave users on a
        // stale bundle indefinitely — and a mismatched bundle vs persisted
        // store can break the login flow entirely.
        skipWaiting: true,
        clientsClaim: true,
        cleanupOutdatedCaches: true,
        // Cache only the app shell; don't cache API responses (the data is
        // collaborative, stale reads are confusing).
        navigateFallbackDenylist: [/^\/api\//],
        runtimeCaching: [
          {
            urlPattern: /\.(?:png|jpg|jpeg|svg|webp)$/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'images',
              expiration: { maxEntries: 100, maxAgeSeconds: 30 * 24 * 60 * 60 },
            },
          },
        ],
      },
      devOptions: { enabled: false },
    }),
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
      '@/components': resolve(__dirname, './src/components'),
      '@/features': resolve(__dirname, './src/features'),
      '@/hooks': resolve(__dirname, './src/hooks'),
      '@/services': resolve(__dirname, './src/services'),
      '@/store': resolve(__dirname, './src/store'),
      '@/utils': resolve(__dirname, './src/utils'),
    },
  },
  server: {
    port: 3000,
    strictPort: true,
  },
  preview: {
    port: 3000,
    proxy: {
      '/mock-images': {
        target: 'http://localhost:4000',
        changeOrigin: true,
      },
    },
  },
  build: {
    // Keep maps for web/Sentry diagnostics, but never package source into a
    // public native binary. The release wrapper sets this process-only flag.
    sourcemap: process.env.MOBILE_STORE_BUILD !== 'true',
    // CQ-19: explicit chunk-size warning (500 KB) as a build-time signal
    // separate from the hard size-limit CI gate (`npm run size`), and pin the
    // build target to Baseline "Widely available" (evergreen browsers with
    // broad real-world support) instead of trusting Vite's implicit default —
    // an explicit, reviewable choice rather than an unstated one.
    chunkSizeWarningLimit: 500,
    target: 'baseline-widely-available',
    rollupOptions: {
      output: {
        manualChunks(id) {
          // Keep the React runtime in a single long-lived vendor chunk.
          // A string-array manualChunks entry (['react', 'react-dom', ...])
          // stopped capturing all of react-dom's submodules under React 19,
          // which leaked the runtime into the entry chunk and ballooned it.
          // Matching on the resolved node_modules path is version-robust.
          if (/node_modules\/(react|react-dom|scheduler|react-router)\//.test(id)) {
            return 'vendor';
          }
          if (/node_modules\/@tanstack\/react-query\//.test(id)) {
            return 'query';
          }
          if (/node_modules\/(@headlessui\/react|@heroicons\/react)\//.test(id)) {
            return 'ui';
          }
          return undefined;
        },
      },
    },
  },
}));
