/**
 * Gift subscriptions — a giver pays once for N months of a paid tier, and a
 * household redeems a code for them (ADR 0028).
 *
 * Priced at the tier's MONTHLY price times the number of months, with no
 * discount. That is deliberate and load-bearing: a discounted twelve-month
 * gift is the annual plan under another name, and the annual plan was
 * withdrawn because at the verified Plant.id cost it earns less per month
 * than the tier's AI-cost ceiling (ADR 0012). A gift month earns exactly
 * what a subscription month earns and is metered exactly the same way.
 *
 * What a gift IS, in code: two attributes on the redeeming household's
 * METADATA row, `giftPlanId` and `giftEndsAt`, read by `giftState` in
 * `models/plans.ts` on every entitlement resolution. The same shape as the
 * no-card trial (ADR 0027): no Stripe customer, subscription or trial stands
 * behind it, nothing renews, nothing can charge the recipient, and it ends
 * because the clock passes a date. Falling back deletes nothing.
 *
 * What a gift is NOT: it is not the buyer's household's purchase. The
 * Checkout Session carries no `householdId` and no `client_reference_id`, so
 * the subscription delta, the lifetime path and the household receipt email
 * all see nothing to act on, and the buyer's housemates are never told what
 * the buyer bought for someone else.
 *
 * The code is a bearer credential. It is generated by the webhook at grant
 * time from the OS CSPRNG, stored only as a hash on the lookup row, shown to
 * the buyer in their own account, never stamped on a Stripe object and never
 * written to a log.
 *
 * Pure module: no DynamoDB, no Stripe client. The dev mock server and the
 * webhook both import it.
 */
import { randomBytes } from 'node:crypto';
import { hashCapabilityToken } from '../utils/tokenHash.js';
import type Stripe from 'stripe';
import { PLANS, isPlanId, type PlanId } from './plans.js';

/** Tiers that can be given. The free tier has nothing to give. */
export type GiftablePlanId = Exclude<PlanId, 'seedling'>;

export const GIFTABLE_PLAN_IDS: readonly GiftablePlanId[] = ['garden', 'greenhouse'];

export function isGiftablePlanId(id: unknown): id is GiftablePlanId {
  return isPlanId(id) && (GIFTABLE_PLAN_IDS as readonly string[]).includes(id);
}

/**
 * Env var carrying the ONE-TIME Stripe price for a single gift month of each
 * tier. Its `unit_amount` must equal the tier's monthly price; checkout
 * reconciles it before minting a Session (`stripePrices.ts`). Unset = that
 * tier cannot be given in this environment, and checkout refuses.
 */
export const GIFT_PRICE_ENV: Record<GiftablePlanId, string> = {
  garden: 'STRIPE_PRICE_ID_GIFT_GARDEN_MONTH',
  greenhouse: 'STRIPE_PRICE_ID_GIFT_GREENHOUSE_MONTH',
};

/** Fewest and most months one gift may carry. Twelve bounds the exposure of a single code. */
export const GIFT_MIN_MONTHS = 1;
export const GIFT_MAX_MONTHS = 12;

/** A code may be redeemed this many days after purchase. The gift itself runs from redemption. */
export const GIFT_REDEEM_WINDOW_DAYS = 365;

/**
 * Metadata marker stamped on the Checkout Session at creation. Every
 * `mode: 'payment'` session needs a positive signal saying what it is; the
 * absence of a `planId` is not one (a malformed lifetime event also lacks it).
 */
export const GIFT_SUBSCRIPTION_PURCHASE_KIND = 'gift_subscription';

export function giftPriceId(planId: GiftablePlanId): string | undefined {
  const raw = process.env[GIFT_PRICE_ENV[planId]];
  if (typeof raw !== 'string') return undefined;
  const trimmed = raw.trim();
  return trimmed === '' ? undefined : trimmed;
}

export function isGiftConfigured(planId: GiftablePlanId): boolean {
  return giftPriceId(planId) !== undefined;
}

export function isValidGiftMonths(months: unknown): months is number {
  return (
    typeof months === 'number' &&
    Number.isInteger(months) &&
    months >= GIFT_MIN_MONTHS &&
    months <= GIFT_MAX_MONTHS
  );
}

/**
 * The amount a gift costs, in cents: the tier's monthly price times the
 * months. Integer arithmetic, because `4.99 * 3` is not `14.97` in IEEE 754.
 * This is what the UI shows and what Stripe must charge (`quantity` on a
 * one-month price); nothing else derives a gift amount.
 */
export function giftAmountCents(planId: GiftablePlanId, months: number): number {
  return Math.round(PLANS[planId].monthlyPrice * 100) * months;
}

export interface GiftSubscriptionSummary {
  minMonths: number;
  maxMonths: number;
  redeemWindowDays: number;
  /** Per tier: true only when payments are on AND a Stripe price is configured. */
  plans: Array<{ planId: GiftablePlanId; available: boolean }>;
}

/**
 * Client-facing projection of the offer. Mirrors `planSummary`'s contract:
 * availability is fail-closed on both gates, and the per-month amount is the
 * tier's `monthlyPrice`, already published (or withheld) by `planSummary`, so
 * no second copy of a price goes over the wire.
 */
export function giftSubscriptionSummary(paymentsAvailable: boolean): GiftSubscriptionSummary {
  return {
    minMonths: GIFT_MIN_MONTHS,
    maxMonths: GIFT_MAX_MONTHS,
    redeemWindowDays: GIFT_REDEEM_WINDOW_DAYS,
    plans: GIFTABLE_PLAN_IDS.map((planId) => ({
      planId,
      available: paymentsAvailable && isGiftConfigured(planId),
    })),
  };
}

// ---------------------------------------------------------------------------
// The code
// ---------------------------------------------------------------------------

/**
 * Crockford base32: no I, L, O or U, so a code read aloud or typed from a
 * card cannot be ambiguous. 16 symbols = 80 bits of CSPRNG entropy, behind a
 * rate-limited redemption endpoint; guessing one is not a realistic attack.
 */
const CODE_ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
const CODE_PREFIX = 'FG';
const CODE_BODY_LENGTH = 16;
const CODE_BODY_PATTERN = /^[0-9A-HJKMNP-TV-Z]{16}$/;

/** Canonical form: `FG` + 16 alphabet symbols, no separators. */
export type GiftCode = string;

export function generateGiftCode(): GiftCode {
  // Each byte masked to 5 bits is a uniform index into a 32-symbol alphabet;
  // 32 divides 256, so there is no modulo bias to reject.
  const bytes = randomBytes(CODE_BODY_LENGTH);
  let body = '';
  for (let i = 0; i < CODE_BODY_LENGTH; i += 1) body += CODE_ALPHABET[bytes[i] & 31];
  return `${CODE_PREFIX}${body}`;
}

/**
 * Canonicalise what a person typed: case, spaces, dashes, and the Crockford
 * confusables (`O`→`0`, `I`/`L`→`1`). Returns null for anything that is not
 * a well-formed code, so a lookup never runs against arbitrary input.
 */
export function normalizeGiftCode(input: unknown): GiftCode | null {
  if (typeof input !== 'string') return null;
  const stripped = input
    .toUpperCase()
    .replace(/[\s\-_]/g, '')
    .replace(/O/g, '0')
    .replace(/[IL]/g, '1');
  if (!stripped.startsWith(CODE_PREFIX)) return null;
  const body = stripped.slice(CODE_PREFIX.length);
  if (!CODE_BODY_PATTERN.test(body)) return null;
  return `${CODE_PREFIX}${body}`;
}

/** `FG-XXXX-XXXX-XXXX-XXXX` — the shape a person reads and copies. */
export function formatGiftCode(code: GiftCode): string {
  const body = code.slice(CODE_PREFIX.length);
  return [CODE_PREFIX, ...(body.match(/.{1,4}/g) ?? [])].join('-');
}

/**
 * The lookup key for a code. Same construction as `calendarTokens.hashToken`
 * and `apiKeys.hashKey` — a fixed, module-specific salt so a gift code can
 * never collide with another token family in the table — and for the same
 * reason: the row must not carry the credential, only a way to recognise it.
 */
export function hashGiftCode(code: GiftCode): string {
  return hashCapabilityToken('giftCode', code);
}

// ---------------------------------------------------------------------------
// Time
// ---------------------------------------------------------------------------

/**
 * `date` plus `months` calendar months, in UTC, with the day clamped to the
 * target month's length: 31 January + 1 month is 28 (or 29) February, never
 * 3 March. `Date.UTC` alone would roll the overflow forward and hand a
 * one-month gift redeemed on the 31st a few extra days — or, on 29–31 March
 * minus a month, the wrong month entirely. The time of day is kept, so the
 * gift ends at the same instant of the day it started.
 */
export function addCalendarMonthsUtc(date: Date, months: number): Date {
  const y = date.getUTCFullYear();
  const m = date.getUTCMonth();
  const d = date.getUTCDate();
  const targetMonthStart = new Date(Date.UTC(y, m + months, 1));
  const daysInTarget = new Date(
    Date.UTC(targetMonthStart.getUTCFullYear(), targetMonthStart.getUTCMonth() + 1, 0)
  ).getUTCDate();
  return new Date(
    Date.UTC(
      targetMonthStart.getUTCFullYear(),
      targetMonthStart.getUTCMonth(),
      Math.min(d, daysInTarget),
      date.getUTCHours(),
      date.getUTCMinutes(),
      date.getUTCSeconds(),
      date.getUTCMilliseconds()
    )
  );
}

// ---------------------------------------------------------------------------
// The Stripe event → grant projection
// ---------------------------------------------------------------------------

/** True when a Checkout Session was minted by `createGiftCheckoutSession`. */
export function isGiftSession(session: { metadata?: Record<string, string> | null }): boolean {
  return session.metadata?.purchase === GIFT_SUBSCRIPTION_PURCHASE_KIND;
}

export interface GiftPurchaseGrant {
  /** Stripe Checkout Session id — the idempotency key of the grant. */
  stripeSessionId: string;
  planId: GiftablePlanId;
  months: number;
  /** The account that paid. The code is shown to this account and nobody else. */
  buyerUserId: string;
  /** ISO timestamp the payment completed; the redeem-by window counts from here. */
  purchasedAt: string;
}

/**
 * The gift a Stripe event describes, or null for anything else.
 *
 * Only a PAID gift checkout grants. `checkout.session.completed` arrives with
 * `payment_status: 'unpaid'` for deferred payment methods; the later
 * `checkout.session.async_payment_succeeded` carries the same session and
 * grants then. Everything the grant needs is read from the metadata stamped
 * at checkout, so the webhook grants what was sold at the time, and a paid
 * session whose metadata is missing or nonsensical returns null — which
 * `applyStripeEvent` turns into the alarmed `stripe_event_paid_no_grant`,
 * never into an invented gift.
 */
export function giftPurchaseFromEvent(event: Stripe.Event): GiftPurchaseGrant | null {
  if (
    event.type !== 'checkout.session.completed' &&
    event.type !== 'checkout.session.async_payment_succeeded'
  ) {
    return null;
  }
  const session = event.data.object as unknown as {
    id?: string;
    mode?: string;
    payment_status?: string;
    metadata?: Record<string, string> | null;
  };
  if (!isGiftSession(session)) return null;
  if (session.mode !== 'payment' || session.payment_status !== 'paid') return null;
  if (typeof session.id !== 'string' || session.id === '') return null;
  const planId = session.metadata?.giftPlanId;
  if (!isGiftablePlanId(planId)) return null;
  const months = Number(session.metadata?.months);
  if (!isValidGiftMonths(months)) return null;
  const buyerUserId = session.metadata?.buyerUserId ?? '';
  if (!buyerUserId) return null;
  return {
    stripeSessionId: session.id,
    planId,
    months,
    buyerUserId,
    purchasedAt: new Date(event.created * 1000).toISOString(),
  };
}
