/**
 * Plant-care RAG: cosine-similarity retrieval over a pre-embedded markdown
 * corpus.
 *
 * The embeddings JSON is generated by `scripts/build-corpus-embeddings.mjs`
 * and imported statically here. esbuild inlines the JSON into the chat
 * handler bundle, so there's nothing to copy at deploy time — the corpus
 * ships as part of the Lambda zip automatically.
 *
 * Latency budget per call: ~200ms for the Titan embed of the query;
 * cosine pass over 74 × 1024-dim vectors is <5ms. Cold start parses the
 * 1.6 MB JSON once (~50ms) and pins it in module scope.
 */
import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime';
import AWSXRay from 'aws-xray-sdk-core';
import corpusJson from '../../data/plant-care-corpus-embeddings.json' with { type: 'json' };

const REGION = process.env.AWS_REGION ?? 'us-east-1';
const EMBED_MODEL = process.env.BEDROCK_EMBED_MODEL_ID || 'amazon.titan-embed-text-v2:0';

const client = AWSXRay.captureAWSv3Client(new BedrockRuntimeClient({ region: REGION }));

interface CorpusChunk {
  source: string;
  articleTitle: string;
  sectionTitle: string;
  text: string;
  embedding: number[];
}

interface CorpusPayload {
  model: string;
  dimensions: number;
  generatedAt: string;
  chunks: CorpusChunk[];
}

// Double-cast through `unknown` to reshape the imported JSON into the typed
// corpus envelope; the `as unknown` step is what the rule flags but it is
// required to bridge the inferred JSON type to CorpusPayload.
// eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
const CORPUS = corpusJson as unknown as CorpusPayload;

/** Cosine similarity. Inputs are assumed normalized (Titan v2 normalized
 *  the corpus at build time; we normalize the query below). */
function cosine(a: number[], b: number[]): number {
  let dot = 0;
  for (let i = 0; i < a.length; i++) dot += a[i] * b[i];
  return dot;
}

function normalize(v: number[]): number[] {
  let sum = 0;
  for (let i = 0; i < v.length; i++) sum += v[i] * v[i];
  const norm = Math.sqrt(sum);
  if (norm === 0) return v;
  return v.map((x) => x / norm);
}

async function embedQuery(text: string): Promise<number[]> {
  const command = new InvokeModelCommand({
    modelId: EMBED_MODEL,
    contentType: 'application/json',
    accept: 'application/json',
    body: JSON.stringify({
      inputText: text,
      dimensions: CORPUS.dimensions,
      normalize: true,
    }),
  });
  const result = await client.send(command);
  const decoded = JSON.parse(new TextDecoder().decode(result.body)) as {
    embedding?: number[];
  };
  if (!Array.isArray(decoded.embedding) || decoded.embedding.length !== CORPUS.dimensions) {
    throw new Error('Embed response missing or wrong-dimension embedding');
  }
  return normalize(decoded.embedding);
}

export interface RetrievedChunk {
  articleTitle: string;
  sectionTitle: string;
  source: string;
  text: string;
  score: number;
}

export async function searchCorpus(query: string, topK = 3): Promise<RetrievedChunk[]> {
  const queryVec = await embedQuery(query);
  const scored = CORPUS.chunks.map((c) => ({
    chunk: c,
    score: cosine(queryVec, c.embedding),
  }));
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, topK).map(({ chunk, score }) => ({
    articleTitle: chunk.articleTitle,
    sectionTitle: chunk.sectionTitle,
    source: chunk.source,
    text: chunk.text,
    score,
  }));
}

/** Test hook — allows tests to bypass Bedrock by supplying a pre-baked
 *  embedding for a known query. Returns the top K against the bundled
 *  corpus using the supplied vector directly. */
export function searchCorpusWithEmbedding(queryVec: number[], topK = 3): RetrievedChunk[] {
  const normalized = normalize(queryVec);
  const scored = CORPUS.chunks.map((c) => ({
    chunk: c,
    score: cosine(normalized, c.embedding),
  }));
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, topK).map(({ chunk, score }) => ({
    articleTitle: chunk.articleTitle,
    sectionTitle: chunk.sectionTitle,
    source: chunk.source,
    text: chunk.text,
    score,
  }));
}
