import { isNativeApp } from '@/lib/platform';

/**
 * iOS/Android Universal Link handling inside the Capacitor shells (#469 §2).
 *
 * The serving side is done: frontend/public/.well-known/apple-app-site-
 * association (generated by `npm run aasa` from ROUTE_POLICY) and the
 * Associated Domains entitlement tell the OS which familygreenhouse.net
 * paths belong to this app. By the time this module's listener fires, the OS
 * has already made that decision — only a claimed path ever reaches
 * `appUrlOpen`. This module's only job is turning that event into an
 * in-app navigation instead of leaving the WebView on whatever it already
 * showed.
 *
 * `@capacitor/app` is imported dynamically and only after an isNativeApp()
 * check, same as nativePush.ts, so web visitors never download it.
 *
 * Uses `history.pushState` + a manual `popstate` dispatch rather than a
 * react-router `navigate()` handle: `<BrowserRouter>` (main.tsx) only
 * re-syncs on `popstate`, which `pushState` does not fire on its own, and
 * this module runs once at boot, outside any component tree, where a
 * `useNavigate()` ref would need extra plumbing this doesn't otherwise need.
 */
export function initNativeDeepLinks(): void {
  if (!isNativeApp()) return;

  void (async () => {
    const { App } = await import('@capacitor/app');
    await App.addListener('appUrlOpen', ({ url }) => {
      let target: URL;
      try {
        target = new URL(url);
      } catch {
        return; // Malformed URL from the OS; nothing sane to navigate to.
      }
      const path = `${target.pathname}${target.search}${target.hash}`;
      window.history.pushState(null, '', path);
      window.dispatchEvent(new PopStateEvent('popstate'));
    });
  })();
}
