#!/usr/bin/env node
/**
 * Emit `public/sitemap.xml` from the shared public-route list. Runs as a
 * `prebuild` step so the generated file is on disk by the time vite copies
 * /public/* into dist/.
 *
 * The route list itself lives in `public-routes.mjs`, which `prerender.mjs`
 * also reads — so the set of URLs we advertise and the set we actually render
 * static HTML for come from one place. `check-prerender-coverage.mjs` proves
 * they stayed equal after the build.
 *
 * Update cadence: blog posts and care guides go through their TS manifests, so
 * they sync automatically. Static pages (/blog, /changelog, /legal/privacy, …)
 * live in STATIC_ROUTES in public-routes.mjs — add to it when you ship a new
 * public route.
 *
 * `--check` (npm run sitemap:check, composed by the root `verify`): build the
 * XML in memory and byte-compare it with the committed file. Nothing is
 * written. This exists because the committed sitemap was a generated artifact
 * that no gate ever compared: `prebuild` runs this script before every
 * `vite build`, so CI's Build, Lighthouse and bundle-size jobs each silently
 * overwrote `public/sitemap.xml` on a clean checkout and threw the result away.
 * A stale sitemap could therefore never fail anywhere — the one process that
 * knew the truth destroyed the evidence before anything looked at it. Search
 * engines, meanwhile, read the committed bytes.
 *
 * `--check` deliberately does NOT regenerate into the working tree. A gate that
 * repairs the artifact it is judging heals drift on the contributor's disk while
 * the committed bytes stay stale, which is precisely how this hides.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { FRONTEND_ROOT, SITE, publicRoutes } from './public-routes.mjs';

const OUT = join(FRONTEND_ROOT, 'public', 'sitemap.xml');

function urlEntry({ path, priority, changefreq, lastmod }) {
  const lines = [
    `  <url>`,
    `    <loc>${SITE}${path}</loc>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority.toFixed(1)}</priority>`,
  ];
  if (lastmod) lines.push(`    <lastmod>${lastmod}</lastmod>`);
  lines.push(`  </url>`);
  return lines.join('\n');
}

/**
 * Build the sitemap XML in memory.
 *
 * Returns the bytes plus `undated`: the routes whose `<lastmod>` fell back to
 * *today's date* because their manifest entry has no `date:` / `reviewed:`
 * (`public-routes.mjs` marks those with an `undated` reason). That fallback is
 * the one source of non-determinism in this generator, and it is reported
 * rather than compared: a byte-compare against a value that changes at
 * midnight is not a gate, and silently excluding those routes would mean the
 * check quietly stopped watching them. No route uses the fallback today.
 */
function buildSitemap() {
  const all = publicRoutes();
  const undated = all
    .filter((route) => route.undated)
    .map((route) => `${route.path} (${route.undated})`);

  const xml = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
    ...all.map(urlEntry),
    `</urlset>`,
    '',
  ].join('\n');

  return { xml, count: all.length, undated };
}

function write() {
  const { xml, count } = buildSitemap();
  writeFileSync(OUT, xml);
  console.log(`Wrote sitemap with ${count} URLs to ${OUT}`);
}

function check() {
  const { xml, count, undated } = buildSitemap();

  if (undated.length > 0) {
    console.error(
      `\n❌ sitemap:check cannot verify ${undated.length} route(s): their <lastmod> falls back\n` +
        `   to today's date, so the committed sitemap is not reproducible tomorrow.\n` +
        undated.map((u) => `   ${u}`).join('\n') +
        `\n\nGive each one an explicit date so the generated bytes are stable.`
    );
    process.exit(1);
  }

  let committed;
  try {
    committed = readFileSync(OUT, 'utf8');
  } catch {
    console.error(`\n❌ ${OUT} does not exist. Run: npm run sitemap`);
    process.exit(1);
  }

  if (committed === xml) {
    console.log(`Sitemap OK — the committed public/sitemap.xml is byte-identical (${count} URLs).`);
    process.exit(0);
  }

  const committedLines = committed.split('\n');
  const builtLines = xml.split('\n');
  console.error(
    `\n❌ public/sitemap.xml has drifted from what build-sitemap.mjs produces.\n` +
      `   Regenerate it with: npm run sitemap --workspace frontend\n`
  );
  const limit = Math.max(committedLines.length, builtLines.length);
  let shown = 0;
  for (let i = 0; i < limit && shown < 40; i += 1) {
    if (committedLines[i] !== builtLines[i]) {
      if (committedLines[i] !== undefined) console.error(`   -${committedLines[i]}`);
      if (builtLines[i] !== undefined) console.error(`   +${builtLines[i]}`);
      shown += 1;
    }
  }
  process.exit(1);
}

if (process.argv.includes('--check')) check();
else write();
