// A curated list of common houseplants, garden ornamentals, herbs, vegetables,
// and fruit/shade trees. Not a complete botanical database; it's here to give
// the AddPlant form a useful first-pass autocomplete without requiring an
// external API. Stored as common-name pairs with their accepted scientific
// name. Sorted by common name for easy scanning when contributing.
//
// To extend: append in alphabetical position. We dedupe by common name
// client-side, so duplicates are harmless but wasteful.
//
// External sources we considered and rejected for now:
//  - Perenual API (free tier, ~10k plants) — sensible upgrade if/when we need
//    images, hardiness zones, or care metadata. Adds API key + rate-limit
//    handling we don't need yet.
//  - Trefle — has been intermittently shut down; status unreliable.
//  - GBIF — free and exhaustive, but it's a taxonomic database for biologists,
//    not a houseplant picker. Returns millions of unrelated species.
export interface SpeciesEntry {
  common: string;
  scientific: string;
}

export const speciesCatalog: SpeciesEntry[] = [
  { common: 'African violet', scientific: 'Saintpaulia ionantha' },
  { common: 'Agave', scientific: 'Agave americana' },
  { common: 'Air plant', scientific: 'Tillandsia' },
  { common: 'Allium', scientific: 'Allium giganteum' },
  { common: 'Aloe vera', scientific: 'Aloe vera' },
  { common: 'Aluminum plant', scientific: 'Pilea cadierei' },
  { common: 'Amaryllis', scientific: 'Hippeastrum' },
  { common: 'Angel wing begonia', scientific: 'Begonia coccinea' },
  { common: 'Anthurium', scientific: 'Anthurium andraeanum' },
  { common: 'Apple', scientific: 'Malus domestica' },
  { common: 'Apricot', scientific: 'Prunus armeniaca' },
  { common: 'Areca palm', scientific: 'Dypsis lutescens' },
  { common: 'Arrowhead plant', scientific: 'Syngonium podophyllum' },
  { common: 'Arugula', scientific: 'Eruca vesicaria' },
  { common: 'Asiatic lily', scientific: 'Lilium asiaticum' },
  { common: 'Asparagus', scientific: 'Asparagus officinalis' },
  { common: 'Asparagus fern', scientific: 'Asparagus setaceus' },
  { common: 'Aster', scientific: 'Symphyotrichum novi-belgii' },
  { common: 'Avocado', scientific: 'Persea americana' },
  { common: 'Azalea', scientific: 'Rhododendron simsii' },
  { common: 'Baby rubber plant', scientific: 'Peperomia obtusifolia' },
  { common: "Baby's breath", scientific: 'Gypsophila paniculata' },
  { common: "Baby's tears", scientific: 'Soleirolia soleirolii' },
  { common: 'Banana plant', scientific: 'Musa acuminata' },
  { common: 'Basil', scientific: 'Ocimum basilicum' },
  { common: 'Bay laurel', scientific: 'Laurus nobilis' },
  { common: 'Bee balm', scientific: 'Monarda didyma' },
  { common: 'Beech', scientific: 'Fagus sylvatica' },
  { common: 'Beet', scientific: 'Beta vulgaris' },
  { common: 'Bell pepper', scientific: 'Capsicum annuum' },
  { common: 'Birch', scientific: 'Betula pendula' },
  { common: "Bird's nest fern", scientific: 'Asplenium nidus' },
  { common: 'Bird of paradise', scientific: 'Strelitzia reginae' },
  { common: 'Birkin philodendron', scientific: "Philodendron 'Birkin'" },
  { common: 'Black-eyed Susan', scientific: 'Rudbeckia hirta' },
  { common: 'Blackberry', scientific: 'Rubus fruticosus' },
  { common: 'Blanket flower', scientific: 'Gaillardia aristata' },
  { common: 'Bleeding heart', scientific: 'Lamprocapnos spectabilis' },
  { common: 'Blueberry', scientific: 'Vaccinium corymbosum' },
  { common: 'Boston fern', scientific: 'Nephrolepis exaltata' },
  { common: 'Bougainvillea', scientific: 'Bougainvillea glabra' },
  { common: 'Boxwood', scientific: 'Buxus sempervirens' },
  { common: 'Brasil philodendron', scientific: "Philodendron hederaceum 'Brasil'" },
  { common: 'Broccoli', scientific: 'Brassica oleracea italica' },
  { common: 'Brussels sprouts', scientific: 'Brassica oleracea gemmifera' },
  { common: "Burro's tail", scientific: 'Sedum morganianum' },
  { common: 'Butterfly bush', scientific: 'Buddleja davidii' },
  { common: 'Butternut squash', scientific: 'Cucurbita moschata' },
  { common: 'Cabbage', scientific: 'Brassica oleracea capitata' },
  { common: 'Calla lily', scientific: 'Zantedeschia aethiopica' },
  { common: 'Camellia', scientific: 'Camellia japonica' },
  { common: 'Cantaloupe', scientific: 'Cucumis melo' },
  { common: 'Carrot', scientific: 'Daucus carota' },
  { common: 'Cast iron plant', scientific: 'Aspidistra elatior' },
  { common: 'Catnip', scientific: 'Nepeta cataria' },
  { common: 'Cattleya orchid', scientific: 'Cattleya labiata' },
  { common: 'Cauliflower', scientific: 'Brassica oleracea botrytis' },
  { common: 'Cebu blue pothos', scientific: 'Epipremnum pinnatum' },
  { common: 'Cedar', scientific: 'Cedrus libani' },
  { common: 'Celery', scientific: 'Apium graveolens' },
  { common: 'Chamomile', scientific: 'Matricaria chamomilla' },
  { common: 'Cherry', scientific: 'Prunus avium' },
  { common: 'Chinese evergreen', scientific: 'Aglaonema commutatum' },
  { common: 'Chinese money plant', scientific: 'Pilea peperomioides' },
  { common: 'Chives', scientific: 'Allium schoenoprasum' },
  { common: 'Christmas cactus', scientific: 'Schlumbergera bridgesii' },
  { common: 'Cilantro', scientific: 'Coriandrum sativum' },
  { common: 'Citronella', scientific: 'Cymbopogon nardus' },
  { common: 'Clematis', scientific: 'Clematis × jackmanii' },
  { common: 'Coconut palm', scientific: 'Cocos nucifera' },
  { common: 'Coffee plant', scientific: 'Coffea arabica' },
  { common: 'Coleus', scientific: 'Plectranthus scutellarioides' },
  { common: 'Coneflower', scientific: 'Echinacea purpurea' },
  { common: 'Coral bells', scientific: 'Heuchera sanguinea' },
  { common: 'Coreopsis', scientific: 'Coreopsis grandiflora' },
  { common: 'Corn', scientific: 'Zea mays' },
  { common: 'Corn plant', scientific: 'Dracaena fragrans' },
  { common: 'Cosmos', scientific: 'Cosmos bipinnatus' },
  { common: 'Crabapple', scientific: 'Malus sylvestris' },
  { common: 'Crape myrtle', scientific: 'Lagerstroemia indica' },
  { common: 'Creeping jenny', scientific: 'Lysimachia nummularia' },
  { common: 'Croton', scientific: 'Codiaeum variegatum' },
  { common: 'Cucumber', scientific: 'Cucumis sativus' },
  { common: 'Cyclamen', scientific: 'Cyclamen persicum' },
  { common: 'Daffodil', scientific: 'Narcissus pseudonarcissus' },
  { common: 'Dahlia', scientific: 'Dahlia pinnata' },
  { common: 'Daisy', scientific: 'Bellis perennis' },
  { common: 'Daylily', scientific: 'Hemerocallis' },
  { common: 'Dendrobium orchid', scientific: 'Dendrobium nobile' },
  { common: "Devil's ivy", scientific: 'Epipremnum aureum' },
  { common: 'Dieffenbachia', scientific: 'Dieffenbachia seguine' },
  { common: 'Dill', scientific: 'Anethum graveolens' },
  { common: 'Dogwood', scientific: 'Cornus florida' },
  { common: 'Dragon tree', scientific: 'Dracaena marginata' },
  { common: 'Dumb cane', scientific: 'Dieffenbachia amoena' },
  { common: 'Easter lily', scientific: 'Lilium longiflorum' },
  { common: 'Echeveria', scientific: 'Echeveria elegans' },
  { common: 'Eggplant', scientific: 'Solanum melongena' },
  { common: 'Elephant ear', scientific: 'Alocasia macrorrhizos' },
  { common: 'Elm', scientific: 'Ulmus americana' },
  { common: 'English ivy', scientific: 'Hedera helix' },
  { common: 'Eucalyptus', scientific: 'Eucalyptus globulus' },
  { common: 'Fiddle leaf fig', scientific: 'Ficus lyrata' },
  { common: 'Fig', scientific: 'Ficus carica' },
  { common: 'Flaming Katy', scientific: 'Kalanchoe blossfeldiana' },
  { common: 'Fluffy ruffle fern', scientific: 'Nephrolepis exaltata "Fluffy Ruffles"' },
  { common: 'Forsythia', scientific: 'Forsythia × intermedia' },
  { common: 'Foxglove', scientific: 'Digitalis purpurea' },
  { common: 'Friendship plant', scientific: 'Pilea involucrata' },
  { common: 'Fuchsia', scientific: 'Fuchsia magellanica' },
  { common: 'Gardenia', scientific: 'Gardenia jasminoides' },
  { common: 'Garlic', scientific: 'Allium sativum' },
  { common: 'Geranium', scientific: 'Pelargonium x hortorum' },
  { common: 'Gerbera daisy', scientific: 'Gerbera jamesonii' },
  { common: 'Ghost plant', scientific: 'Graptopetalum paraguayense' },
  { common: 'Ginkgo', scientific: 'Ginkgo biloba' },
  { common: 'Gladiolus', scientific: 'Gladiolus hortulanus' },
  { common: 'Goldenrod', scientific: 'Solidago canadensis' },
  { common: 'Goldfish plant', scientific: 'Columnea gloriosa' },
  { common: 'Grape', scientific: 'Vitis vinifera' },
  { common: 'Grape hyacinth', scientific: 'Muscari armeniacum' },
  { common: 'Hardy hibiscus', scientific: 'Hibiscus moscheutos' },
  { common: 'Hawaiian umbrella plant', scientific: 'Schefflera arboricola' },
  { common: 'Hawthorn', scientific: 'Crataegus monogyna' },
  { common: 'Hens and chicks', scientific: 'Sempervivum tectorum' },
  { common: 'Hibiscus', scientific: 'Hibiscus rosa-sinensis' },
  { common: 'Hindu rope hoya', scientific: "Hoya carnosa 'Compacta'" },
  { common: 'Holly', scientific: 'Ilex aquifolium' },
  { common: 'Honeysuckle', scientific: 'Lonicera japonica' },
  { common: 'Hosta', scientific: 'Hosta plantaginea' },
  { common: 'Hot pepper', scientific: 'Capsicum annuum' },
  { common: 'Hoya', scientific: 'Hoya carnosa' },
  { common: 'Hyacinth', scientific: 'Hyacinthus orientalis' },
  { common: 'Hydrangea', scientific: 'Hydrangea macrophylla' },
  { common: 'Impatiens', scientific: 'Impatiens walleriana' },
  { common: 'Inch plant', scientific: 'Tradescantia zebrina' },
  { common: 'Iris', scientific: 'Iris germanica' },
  { common: 'Jade plant', scientific: 'Crassula ovata' },
  { common: 'Janet Craig dracaena', scientific: 'Dracaena deremensis "Janet Craig"' },
  { common: 'Japanese maple', scientific: 'Acer palmatum' },
  { common: 'Jasmine', scientific: 'Jasminum officinale' },
  { common: 'Juniper', scientific: 'Juniperus communis' },
  { common: 'Kale', scientific: 'Brassica oleracea acephala' },
  { common: 'Kangaroo paw', scientific: 'Anigozanthos flavidus' },
  { common: 'Kentia palm', scientific: 'Howea forsteriana' },
  { common: 'Kiwi', scientific: 'Actinidia deliciosa' },
  { common: 'Kohlrabi', scientific: 'Brassica oleracea gongylodes' },
  { common: 'Lady palm', scientific: 'Rhapis excelsa' },
  { common: 'Lambs ear', scientific: 'Stachys byzantina' },
  { common: 'Lantana', scientific: 'Lantana camara' },
  { common: 'Lavender', scientific: 'Lavandula angustifolia' },
  { common: 'Leek', scientific: 'Allium ampeloprasum' },
  { common: 'Lemon', scientific: 'Citrus limon' },
  { common: 'Lemon balm', scientific: 'Melissa officinalis' },
  { common: 'Lemon button fern', scientific: 'Nephrolepis cordifolia "Duffii"' },
  { common: 'Lemon verbena', scientific: 'Aloysia citrodora' },
  { common: 'Lemongrass', scientific: 'Cymbopogon citratus' },
  { common: 'Lettuce', scientific: 'Lactuca sativa' },
  { common: 'Lilac', scientific: 'Syringa vulgaris' },
  { common: 'Lily of the valley', scientific: 'Convallaria majalis' },
  { common: 'Lime', scientific: 'Citrus aurantiifolia' },
  { common: 'Lipstick plant', scientific: 'Aeschynanthus radicans' },
  { common: 'Living stones', scientific: 'Lithops' },
  { common: 'Lobelia', scientific: 'Lobelia erinus' },
  { common: 'Lucky bamboo', scientific: 'Dracaena sanderiana' },
  { common: 'Madagascar dragon tree', scientific: 'Dracaena marginata' },
  { common: 'Magnolia', scientific: 'Magnolia grandiflora' },
  { common: 'Maidenhair fern', scientific: 'Adiantum raddianum' },
  { common: 'Majesty palm', scientific: 'Ravenea rivularis' },
  { common: 'Mango', scientific: 'Mangifera indica' },
  { common: 'Marble queen pothos', scientific: 'Epipremnum aureum "Marble Queen"' },
  { common: 'Marigold', scientific: 'Tagetes erecta' },
  { common: 'Marjoram', scientific: 'Origanum majorana' },
  { common: 'Medallion calathea', scientific: "Calathea roseopicta 'Medallion'" },
  { common: 'Milkweed', scientific: 'Asclepias syriaca' },
  { common: 'Mint', scientific: 'Mentha spicata' },
  { common: 'Mistletoe cactus', scientific: 'Rhipsalis baccifera' },
  { common: 'Money tree', scientific: 'Pachira aquatica' },
  { common: 'Monstera', scientific: 'Monstera deliciosa' },
  { common: 'Morning glory', scientific: 'Ipomoea purpurea' },
  { common: 'Moss rose', scientific: 'Portulaca grandiflora' },
  { common: 'Moth orchid', scientific: 'Phalaenopsis' },
  { common: 'Mum', scientific: 'Chrysanthemum morifolium' },
  { common: 'Mustard greens', scientific: 'Brassica juncea' },
  { common: 'Nasturtium', scientific: 'Tropaeolum majus' },
  { common: 'Nectarine', scientific: 'Prunus persica nucipersica' },
  { common: 'Neon pothos', scientific: 'Epipremnum aureum "Neon"' },
  { common: 'Nerve plant', scientific: 'Fittonia albivenis' },
  { common: 'Norfolk Island pine', scientific: 'Araucaria heterophylla' },
  { common: 'Oak', scientific: 'Quercus rubra' },
  { common: 'Okra', scientific: 'Abelmoschus esculentus' },
  { common: 'Oleander', scientific: 'Nerium oleander' },
  { common: 'Olive', scientific: 'Olea europaea' },
  { common: 'Oncidium orchid', scientific: 'Oncidium' },
  { common: 'Onion', scientific: 'Allium cepa' },
  { common: 'Orange', scientific: 'Citrus sinensis' },
  { common: 'Orbifolia calathea', scientific: 'Calathea orbifolia' },
  { common: 'Oregano', scientific: 'Origanum vulgare' },
  { common: 'Oxalis', scientific: 'Oxalis triangularis' },
  { common: 'Painted leaf begonia', scientific: 'Begonia rex' },
  { common: 'Panda plant', scientific: 'Kalanchoe tomentosa' },
  { common: 'Pansy', scientific: 'Viola tricolor' },
  { common: 'Papaya', scientific: 'Carica papaya' },
  { common: 'Parlor palm', scientific: 'Chamaedorea elegans' },
  { common: 'Parsley', scientific: 'Petroselinum crispum' },
  { common: 'Parsnip', scientific: 'Pastinaca sativa' },
  { common: 'Passion flower', scientific: 'Passiflora caerulea' },
  { common: 'Peace lily', scientific: 'Spathiphyllum wallisii' },
  { common: 'Peach', scientific: 'Prunus persica' },
  { common: 'Peacock plant', scientific: 'Calathea makoyana' },
  { common: 'Pear', scientific: 'Pyrus communis' },
  { common: 'Peas', scientific: 'Pisum sativum' },
  { common: 'Pecan', scientific: 'Carya illinoinensis' },
  { common: 'Penstemon', scientific: 'Penstemon barbatus' },
  { common: 'Peony', scientific: 'Paeonia lactiflora' },
  { common: 'Peperomia', scientific: 'Peperomia obtusifolia' },
  { common: 'Peppermint', scientific: 'Mentha × piperita' },
  { common: 'Periwinkle', scientific: 'Vinca minor' },
  { common: 'Persimmon', scientific: 'Diospyros kaki' },
  { common: 'Petunia', scientific: 'Petunia × hybrida' },
  { common: 'Philodendron', scientific: 'Philodendron hederaceum' },
  { common: 'Phlox', scientific: 'Phlox paniculata' },
  { common: 'Pineapple', scientific: 'Ananas comosus' },
  { common: 'Pink princess philodendron', scientific: "Philodendron erubescens 'Pink Princess'" },
  { common: 'Pinstripe plant', scientific: 'Calathea ornata' },
  { common: 'Plumeria', scientific: 'Plumeria rubra' },
  { common: 'Polka dot plant', scientific: 'Hypoestes phyllostachya' },
  { common: 'Pomegranate', scientific: 'Punica granatum' },
  { common: 'Ponytail palm', scientific: 'Beaucarnea recurvata' },
  { common: 'Poppy', scientific: 'Papaver orientale' },
  { common: 'Potato', scientific: 'Solanum tuberosum' },
  { common: 'Pothos', scientific: 'Epipremnum aureum' },
  { common: 'Prayer plant', scientific: 'Maranta leuconeura' },
  { common: 'Primrose', scientific: 'Primula vulgaris' },
  { common: 'Pumpkin', scientific: 'Cucurbita pepo' },
  { common: 'Purple shamrock', scientific: 'Oxalis triangularis' },
  { common: 'Queen of hearts', scientific: 'Homalomena rubescens' },
  { common: "Rabbit's foot fern", scientific: 'Davallia fejeensis' },
  { common: 'Radish', scientific: 'Raphanus sativus' },
  { common: 'Raspberry', scientific: 'Rubus idaeus' },
  { common: 'Rattlesnake plant', scientific: 'Calathea lancifolia' },
  { common: 'Red prayer plant', scientific: 'Maranta leuconeura erythroneura' },
  { common: 'Redbud', scientific: 'Cercis canadensis' },
  { common: 'Rex begonia', scientific: 'Begonia rex' },
  { common: 'Rhododendron', scientific: 'Rhododendron ponticum' },
  { common: 'Rhubarb', scientific: 'Rheum rhabarbarum' },
  { common: 'Rose', scientific: 'Rosa' },
  { common: 'Rose of Sharon', scientific: 'Hibiscus syriacus' },
  { common: 'Roselle', scientific: 'Hibiscus sabdariffa' },
  { common: 'Rosemary', scientific: 'Salvia rosmarinus' },
  { common: 'Rubber plant', scientific: 'Ficus elastica' },
  { common: 'Rutabaga', scientific: 'Brassica napobrassica' },
  { common: 'Sage', scientific: 'Salvia officinalis' },
  { common: 'Sago palm', scientific: 'Cycas revoluta' },
  { common: 'Sansevieria', scientific: 'Dracaena trifasciata' },
  { common: 'Satin pothos', scientific: 'Scindapsus pictus' },
  { common: 'Schefflera', scientific: 'Schefflera actinophylla' },
  { common: 'Scotch pine', scientific: 'Pinus sylvestris' },
  { common: 'Shasta daisy', scientific: 'Leucanthemum × superbum' },
  { common: 'Snake plant', scientific: 'Dracaena trifasciata' },
  { common: 'Snapdragon', scientific: 'Antirrhinum majus' },
  { common: 'Snowdrop', scientific: 'Galanthus nivalis' },
  { common: 'Spider plant', scientific: 'Chlorophytum comosum' },
  { common: 'Spinach', scientific: 'Spinacia oleracea' },
  { common: 'Split-leaf philodendron', scientific: 'Monstera deliciosa' },
  { common: 'Staghorn fern', scientific: 'Platycerium bifurcatum' },
  { common: 'Stevia', scientific: 'Stevia rebaudiana' },
  { common: 'Strawberry', scientific: 'Fragaria × ananassa' },
  { common: 'String of bananas', scientific: 'Curio radicans' },
  { common: 'String of dolphins', scientific: 'Curio peregrinus' },
  { common: 'String of hearts', scientific: 'Ceropegia woodii' },
  { common: 'String of pearls', scientific: 'Curio rowleyanus' },
  { common: 'String of turtles', scientific: 'Peperomia prostrata' },
  { common: 'Sugar maple', scientific: 'Acer saccharum' },
  { common: 'Summer squash', scientific: 'Cucurbita pepo' },
  { common: 'Sunflower', scientific: 'Helianthus annuus' },
  { common: 'Swedish ivy', scientific: 'Plectranthus verticillatus' },
  { common: 'Sweet potato', scientific: 'Ipomoea batatas' },
  { common: 'Sweet violet', scientific: 'Viola odorata' },
  { common: 'Sweetheart hoya', scientific: 'Hoya kerrii' },
  { common: 'Swiss chard', scientific: 'Beta vulgaris cicla' },
  { common: 'Swiss cheese plant', scientific: 'Monstera adansonii' },
  { common: 'Tarragon', scientific: 'Artemisia dracunculus' },
  { common: 'Thyme', scientific: 'Thymus vulgaris' },
  { common: 'Tomato', scientific: 'Solanum lycopersicum' },
  { common: 'Tradescantia', scientific: 'Tradescantia zebrina' },
  { common: 'Tropical hibiscus', scientific: 'Hibiscus rosa-sinensis' },
  { common: 'Tulip', scientific: 'Tulipa gesneriana' },
  { common: 'Turnip', scientific: 'Brassica rapa' },
  { common: 'Turtle vine', scientific: 'Callisia repens' },
  { common: 'Umbrella plant', scientific: 'Schefflera arboricola' },
  { common: 'Vanda orchid', scientific: 'Vanda coerulea' },
  { common: 'Variegated monstera', scientific: 'Monstera deliciosa "Variegata"' },
  { common: 'Velvet leaf philodendron', scientific: 'Philodendron micans' },
  { common: 'Venus flytrap', scientific: 'Dionaea muscipula' },
  { common: 'Verbena', scientific: 'Verbena × hybrida' },
  { common: 'Vinca', scientific: 'Catharanthus roseus' },
  { common: 'Viola', scientific: 'Viola cornuta' },
  { common: 'Wandering jew', scientific: 'Tradescantia zebrina' },
  { common: 'Watermelon', scientific: 'Citrullus lanatus' },
  { common: 'Watermelon peperomia', scientific: 'Peperomia argyreia' },
  { common: 'Wax plant', scientific: 'Hoya carnosa' },
  { common: 'Weeping fig', scientific: 'Ficus benjamina' },
  { common: 'White fusion calathea', scientific: "Calathea lietzei 'White Fusion'" },
  { common: 'Wisteria', scientific: 'Wisteria sinensis' },
  { common: 'Yarrow', scientific: 'Achillea millefolium' },
  { common: 'Yew', scientific: 'Taxus baccata' },
  { common: 'Yucca', scientific: 'Yucca elephantipes' },
  { common: 'Zinnia', scientific: 'Zinnia elegans' },
  { common: 'Zucchini', scientific: 'Cucurbita pepo' },
  { common: 'ZZ plant', scientific: 'Zamioculcas zamiifolia' },
];

/**
 * Score a species entry against a query. Higher is better. Returns 0 when
 * the entry should be excluded entirely.
 */
function score(entry: SpeciesEntry, normalized: string): number {
  const common = entry.common.toLowerCase();
  const scientific = entry.scientific.toLowerCase();
  if (common === normalized || scientific === normalized) return 100;
  if (common.startsWith(normalized)) return 80;
  if (scientific.startsWith(normalized)) return 70;
  if (common.includes(normalized)) return 50;
  if (scientific.includes(normalized)) return 40;
  return 0;
}

export function searchSpecies(query: string, limit = 10): SpeciesEntry[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [];
  return speciesCatalog
    .map((entry) => ({ entry, s: score(entry, normalized) }))
    .filter((row) => row.s > 0)
    .sort((a, b) => b.s - a.s || a.entry.common.localeCompare(b.entry.common))
    .slice(0, limit)
    .map((row) => row.entry);
}
